//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerOfGeneralUser.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int id { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNumber { get; set; }
        public int OwnerID { get; set; }
    
        public virtual UserVM UserVM { get; set; }
    }
}
